// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"

	"github.com/vmpyr/afterlight/internal/core"
)

type Artifact struct {
	ID            string             `json:"id"`
	VaultID       string             `json:"vault_id"`
	MessageType   core.MessageType   `json:"message_type"`
	EncryptedBlob core.EncryptedBlob `json:"encrypted_blob"`
	Iv            string             `json:"iv"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Beneficiary struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	Name         string       `json:"name"`
	IsVerifier   sql.NullBool `json:"is_verifier"`
	HasConfirmed sql.NullBool `json:"has_confirmed"`
	ConfirmedAt  sql.NullTime `json:"confirmed_at"`
	CreatedAt    time.Time    `json:"created_at"`
}

type ContactMethod struct {
	ID            string         `json:"id"`
	UserID        sql.NullString `json:"user_id"`
	BeneficiaryID sql.NullString `json:"beneficiary_id"`
	Channel       string         `json:"channel"`
	Target        string         `json:"target"`
	Metadata      core.Metadata  `json:"metadata"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Session struct {
	Token     string       `json:"token"`
	UserID    string       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID                 string          `json:"id"`
	Name               string          `json:"name"`
	Email              string          `json:"email"`
	PasswordHash       string          `json:"password_hash"`
	IsPaused           bool            `json:"is_paused"`
	CheckInInterval    int64           `json:"check_in_interval"`
	TriggerIntervalNum int64           `json:"trigger_interval_num"`
	BufferPeriod       int64           `json:"buffer_period"`
	VerifierQuorum     sql.NullInt64   `json:"verifier_quorum"`
	LastCheckIn        time.Time       `json:"last_check_in"`
	CurrentStatus      core.UserStatus `json:"current_status"`
	CreatedAt          time.Time       `json:"created_at"`
}

type Vault struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	KdfSalt   string    `json:"kdf_salt"`
	CreatedAt time.Time `json:"created_at"`
}

type VaultAccess struct {
	VaultID       string         `json:"vault_id"`
	BeneficiaryID string         `json:"beneficiary_id"`
	Hint          sql.NullString `json:"hint"`
}
